version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: my-node-app

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NODE_ENV: development

    restart: unless-stopped

    command: npm run dev

    stdin_open: true
    tty: true
